# Generated by Django 3.2.8 on 2021-10-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('idx', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('rating_count', models.FloatField(blank=True, null=True)),
                ('install_number', models.FloatField()),
                ('price', models.FloatField()),
                ('size', models.CharField(max_length=255)),
                ('system_required', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=255)),
                ('age_required', models.CharField(max_length=255)),
                ('ad_support', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'google_store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppInfo_Mongo',
            fields=[
                ('idx', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('rating_count', models.FloatField(blank=True, null=True)),
                ('install_number', models.FloatField()),
                ('price', models.FloatField()),
                ('size', models.CharField(max_length=255)),
                ('system_required', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=255)),
                ('age_required', models.CharField(max_length=255)),
                ('ad_support', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'google_store',
            },
        ),
    ]
